CREATE DATABASE GirlStore;
USE GirlStore;
CREATE TABLE Users(
IdUser INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
UserName VARCHAR (50) NOT NULL,
Phone VARCHAR (15) NOT NULL,
Email VARCHAR (50) NOT NULL,
Pswd VARCHAR (100) NOT NULL,
Direction VARCHAR (100) NOT NULL
);



